<%@ page language="java" contentType="text/html; charset=EUC-KR"
    pageEncoding="EUC-KR"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=EUC-KR">
<title>Insert title here</title>
</head>
<script type="text/javascript" src="<%=request.getContextPath()%>/JavascriptUtil/util.js"></script>

<body>
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하

zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하

zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하
zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하zzzzzz김현하

<input type="button" value="aaaaaa" onclick="gg()"/>

<script type="text/javascript">
window.onload=function(){
	alert(window.opener.namegaga);
};

function gg(){
	WindowUtil.closeOpener();
	WindowUtil.closeOpener();
}
function haha(a){
	alert(a);
}
</script>
</body>
</html>